ci: add jobs

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -95,7 +95,28 @@ jobs:
       - name: Size check
         run: npm run size-check
 
-  build:
+  check-npm-token:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "22.5.1"
+          registry-url: "https://registry.npmjs.org"
+
+      - name: Verify NPM Token
+        run: |
+          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
+          if npm whoami > /dev/null 2>&1; then
+            echo "✅ NPM token is valid. Logged in as: $(npm whoami)"
+          else
+            echo "❌ NPM token is invalid or expired." >&2
+            exit 1
+          fi
+        env:
+          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+
+  dry-run-npm-publish:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -105,12 +126,16 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: "22.5.1"
+          registry-url: "https://registry.npmjs.org"
 
       - name: Install dependencies
         run: npm ci
 
       - name: Build
         run: npm run build
+
+      - name: Dry run publish to NPM
+        run: npm publish --dry-run
 
   # e2e: {}
 
@@ -121,7 +146,8 @@ jobs:
       - lint
       - unit
       - size-check
-      - build
+      - check-npm-token
+      - dry-run-npm-publish
       # - e2e
     permissions:
       actions: read
